### ISSUE TITLE
predict2tag might not good 

### ISSUE THREAD

**Issue by jcjview** [renjunxiang/Competiton_CAIL#2]
While running  this model, I use data_train for train and use both data_valid and data_test for validation.
I got bst model in epoch=7.
In data_valid I got 
normal avg_f1 score 0.6635
predict2toptag avg_f1_score 0.5135
predict2tag avg_f1_score 0.5769
In data_test  I got 
normal  avg_f1_score 0.6410 
predict2toptag avg_f1_score 0.5564 
predict2tag  avg_f1_score 0.5589 
 Maybe some of your code haven't push to repo?

**Comment by renjunxiang** [comment]
I'm sorry for answering you at this moment bacause busy recently.
My full code haven't push to repo bacause organizers warned me if others' submission same as mine, both will be invalid.
So it was only a method, I have some changes in processing and neural network. 
Processing is much more important than model.
And I only use accuracy instead of f1_score because in several submissions I found high accuracy got high score. But f1_score dosen't.

**Comment by jcjview** [comment]
Thank you for the response.
